#!/bin/bash
# Auto Scouter Supabase Migration Setup Script

echo "�� Auto Scouter Supabase Migration Setup"
echo "========================================"
echo ""
echo "STEP 1: Create Supabase Project"
echo "1. Go to https://supabase.com"
echo "2. Sign up/Login and create new project"
echo "3. Name: auto-scouter-global"
echo "4. Region: Europe (for Italy access)"
echo ""
echo "STEP 2: Get Project Details"
echo "From your Supabase dashboard (Settings → API):"
echo "- Project URL"
echo "- Anon Key"
echo "- Service Role Key"
echo ""
echo "STEP 3: Run Database Migration"
echo "In Supabase SQL Editor, run: supabase_migration.sql"
echo ""
echo "STEP 4: Deploy Edge Functions"
echo "supabase functions deploy vehicle-api"
echo "supabase functions deploy vehicle-scraper"
echo ""
echo "STEP 5: Migrate Data"
echo "python3 migrate_data_to_supabase.py"
echo ""
echo "STEP 6: Build Global APK"
echo "cd frontend && npm run build && npx cap sync android"
echo "cd android && ./gradlew assembleRelease"
echo ""
echo "✅ Your global Auto Scouter will be ready!"
