web: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
worker: python -m celery worker -A app.tasks.celery_app --loglevel=info
beat: python -m celery beat -A app.tasks.celery_app --loglevel=info
